import 'package:flutter/material.dart';
import 'package:hassaniya_translation/pages%20/home_page.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core

// Import your Firebase options file (generated by FlutterFire CLI)
// Make sure this path matches your actual file location.
import 'firebase_options.dart';

void main() async{
  WidgetsFlutterBinding.ensureInitialized(); // Required for Firebase.initializeApp()
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hassaniya Collector',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        useMaterial3: true,
      ),
      home: const HomePage(),
    );
  }
}
